<?php

namespace lang_tools;


// includes
require_once __DIR__.'/../basic_parser/object.php';

// includes for used modules

// Enum lang_e
const lang_e__UNDEF                = 0;
const lang_e__AB                   = 1;
const lang_e__AA                   = 2;
const lang_e__AF                   = 3;
const lang_e__AK                   = 4;
const lang_e__SQ                   = 5;
const lang_e__AM                   = 6;
const lang_e__AR                   = 7;
const lang_e__AN                   = 8;
const lang_e__HY                   = 9;
const lang_e__AS                   = 10;
const lang_e__AV                   = 11;
const lang_e__AZ                   = 12;
const lang_e__BM                   = 13;
const lang_e__BA                   = 14;
const lang_e__BE                   = 15;
const lang_e__BN                   = 16;
const lang_e__BH                   = 17;
const lang_e__BI                   = 18;
const lang_e__BS                   = 19;
const lang_e__BR                   = 20;
const lang_e__BG                   = 21;
const lang_e__MY                   = 22;
const lang_e__CA                   = 23;
const lang_e__CH                   = 24;
const lang_e__CE                   = 25;
const lang_e__NY                   = 26;
const lang_e__ZH                   = 27;
const lang_e__CV                   = 28;
const lang_e__KW                   = 29;
const lang_e__CO                   = 30;
const lang_e__CR                   = 31;
const lang_e__HR                   = 32;
const lang_e__CS                   = 33;
const lang_e__DA                   = 34;
const lang_e__DV                   = 35;
const lang_e__NL                   = 36;
const lang_e__DZ                   = 37;
const lang_e__EN                   = 38;
const lang_e__ET                   = 39;
const lang_e__EE                   = 40;
const lang_e__FO                   = 41;
const lang_e__FJ                   = 42;
const lang_e__FI                   = 43;
const lang_e__FR                   = 44;
const lang_e__FF                   = 45;
const lang_e__GL                   = 46;
const lang_e__KA                   = 47;
const lang_e__DE                   = 48;
const lang_e__EL                   = 49;
const lang_e__GN                   = 50;
const lang_e__HT                   = 51;
const lang_e__HZ                   = 52;
const lang_e__HO                   = 53;
const lang_e__HU                   = 54;
const lang_e__ID                   = 55;
const lang_e__GA                   = 56;
const lang_e__IG                   = 57;
const lang_e__IK                   = 58;
const lang_e__IO                   = 59;
const lang_e__IS                   = 60;
const lang_e__IT                   = 61;
const lang_e__JV                   = 62;
const lang_e__KL                   = 63;
const lang_e__KN                   = 64;
const lang_e__KR                   = 65;
const lang_e__KK                   = 66;
const lang_e__KM                   = 67;
const lang_e__KI                   = 68;
const lang_e__KY                   = 69;
const lang_e__KV                   = 70;
const lang_e__KG                   = 71;
const lang_e__LB                   = 72;
const lang_e__LG                   = 73;
const lang_e__LI                   = 74;
const lang_e__LN                   = 75;
const lang_e__LO                   = 76;
const lang_e__LT                   = 77;
const lang_e__LUB                  = 78;
const lang_e__LV                   = 79;
const lang_e__GV                   = 80;
const lang_e__MK                   = 81;
const lang_e__MG                   = 82;
const lang_e__ML                   = 83;
const lang_e__MT                   = 84;
const lang_e__MI                   = 85;
const lang_e__MH                   = 86;
const lang_e__MN                   = 87;
const lang_e__NA                   = 88;
const lang_e__NV                   = 89;
const lang_e__ND                   = 90;
const lang_e__NE                   = 91;
const lang_e__NB                   = 92;
const lang_e__NN                   = 93;
const lang_e__NO                   = 94;
const lang_e__II                   = 95;
const lang_e__NR                   = 96;
const lang_e__OC                   = 97;
const lang_e__OJ                   = 98;
const lang_e__OM                   = 99;
const lang_e__OR                   = 100;
const lang_e__OS                   = 101;
const lang_e__PI                   = 102;
const lang_e__PL                   = 103;
const lang_e__PT                   = 104;
const lang_e__QU                   = 105;
const lang_e__RM                   = 106;
const lang_e__RO                   = 107;
const lang_e__RU                   = 108;
const lang_e__SC                   = 109;
const lang_e__SM                   = 110;
const lang_e__SG                   = 111;
const lang_e__SR                   = 112;
const lang_e__GD                   = 113;
const lang_e__SN                   = 114;
const lang_e__SI                   = 115;
const lang_e__SK                   = 116;
const lang_e__SL                   = 117;
const lang_e__SO                   = 118;
const lang_e__ST                   = 119;
const lang_e__ES                   = 120;
const lang_e__SU                   = 121;
const lang_e__SW                   = 122;
const lang_e__SS                   = 123;
const lang_e__SV                   = 124;
const lang_e__TA                   = 125;
const lang_e__TE                   = 126;
const lang_e__TH                   = 127;
const lang_e__TI                   = 128;
const lang_e__BO                   = 129;
const lang_e__TK                   = 130;
const lang_e__TL                   = 131;
const lang_e__TN                   = 132;
const lang_e__TO                   = 133;
const lang_e__TR                   = 134;
const lang_e__TS                   = 135;
const lang_e__TY                   = 136;
const lang_e__UK                   = 137;
const lang_e__VE                   = 138;
const lang_e__VI                   = 139;
const lang_e__WA                   = 140;
const lang_e__CY                   = 141;
const lang_e__WO                   = 142;
const lang_e__FY                   = 143;
const lang_e__XH                   = 144;
const lang_e__YO                   = 145;
const lang_e__ZA                   = 146;
const lang_e__ZU                   = 147;

# namespace_end lang_tools


?>

